### ISSUE TITLE
Cannot bootstrap from git: ./configure detects 14.01.1 as not "sufficiently recent"

### ISSUE THREAD

**Issue by ulidtko** [Mercury-Language/mercury#35]
Repro steps:

    $ URL=http://dl.mercurylang.org/release/mercury-srcdist-14.01.1.tar.gz
    $ curl $URL | tar xj && cd mercury-srcdist-14.01.1
    $ ./configure --enable-minimal-install && make all install
     ...
    $ PATH=$PATH:/usr/local/mercury-14.01.1/bin
    $
    $ which mmc; mmc --version
    /usr/local/mercury-14.01.1/bin/mmc
    Mercury Compiler, version 14.01.1, configured for x86_64-unknown-linux-gnu
    Copyright (C) 1993-2014 The University of Melbourne
    $
    $ cd ~/src/mercury.git
    $ ./configure
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables... 
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking what the C compiler type really is... gcc
    checking build system type... x86_64-pc-linux-gnu
    checking host system type... x86_64-pc-linux-gnu
    checking for cygpath... echo
    checking for cygpath... echo
    looking for an already installed Mercury compiler to bootstrap with...
    checking for mmc... /usr/local/mercury-14.01.1/bin/mmc
    checking whether the above mmc works and is sufficiently recent... no
    configure: error: You need a working Mercury compiler to bootstrap with

Actual result: the test program extracted from `configure.ac:354-492` as `conftest.m` doesn't compile with mmc 14.01.1:
```
$ mmc /tmp/conftest.m 
/tmp/conftest.m:004: Error: no clauses for predicate `main'/2.
/tmp/conftest.m:014: Error: malformed attribute list in mutable declaration:
/tmp/conftest.m:014:   [[untrailed, attach_to_io_state, thread_local]].
/tmp/conftest.m:034: Error: invalid trace goal parameter `[io((! S))]'.
/tmp/conftest.m:089: Error: expected a valid mapping element.
/tmp/conftest.m:089:   , not `[(c_enum_1 - "enum1"), (c_enum_2 - "enum2")]'.
/tmp/conftest.m:093: Error: invalid assertion in `:- pragma foreign_type'
/tmp/conftest.m:093:   declaration.
/tmp/conftest.m:096: Error: invalid `:- pragma foreign_proc' declaration:
/tmp/conftest.m:096:   invalid second argument: expecting a foreign proc
/tmp/conftest.m:096:   attribute or list of attributes.
/tmp/conftest.m:132: Error: no clauses for predicate `ext'/1.
/tmp/conftest.m:133: Error: unrecognized declaration:
/tmp/conftest.m:133:   (pragma external_pred((ext / 1))).
```

Expected result: bootstrapping doesn't depend on unreleased-yet features and can happen from current stable release.

**Comment by zsomogyi** [comment]
On Fri, 09 Oct 2015 04:57:20 -0700, Maxim Ivanov <notifications@github.com> wrote:
> Expected result: bootstrapping doesn't depend on unreleased-yet features and can happen from current stable release.

You may expect that, but it is explicitly NOT an objective for us.
When we improve the language or the implementation, we don't
want to wait a year before using the improvement.

If you want to compile a workspace checked out from git, you will need
a recent release-of-the-day.

Zoltan.

**Comment by ulidtko** [comment]
Ok, so this is by design.

Got you.
